# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Rob Blue
description: "Bridging Data & Business—I'm Rob, a Data Scientist focused on insights that drive results. Explore my work below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Houston, TX"
resume_url: /docs/Data Science Project Lead Resume.docx
avatar_image: /img/Profile Pic Cropped.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/robertbluemsds/" 
github: "https://github.com/robert-blue-datascience" 

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

